version: '3.8'

services:
  daynotes-app:
    image: shubhammca88/daynotes-app:latest
    ports:
      - "8000:8000"
    environment:
      - DEBUG=False
    restart: unless-stopped
    volumes:
      - ./data:/app/data